version: '3.8'

services:
  db:
    image: postgres:15
    container_name: shop_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=19762003
      - POSTGRES_DB=shop_db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: shop_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:19762003@db:5432/shop_db